<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use App\Http\Controllers\AdminController;
use App\User;
use App\Post;

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		Model::unguard();

		$this->call('UserTableSeeder');
		$this->call('PostsTableSeeder');
	}

}

class UserTableSeeder extends Seeder {

    public function run()
    {  
        DB::table('users')->delete();
        User::create(array(
            'username' => 'admin',
            'password' => Hash::make('admin'),
            'isAdmin' => '1'
        ));
    }
}

class PostsTableSeeder extends Seeder{
	
	public function run()
	{
		$faker = Faker\Factory::create();
		$aC = new AdminController;
		$post = new Post;

		Post::truncate();

		foreach (range(1, 30) as $index)
		{
			//setting up data for seeding
			$data = array(
				"title" => $faker->sentence,
				"draft" => "0",
				"body" => $faker->paragraph(50),
				"image" => $faker->imageUrl(360, 225)
			);

			//getting a unique slug of the title generated by the Faker using our method getSlug()
			//in AdminController
			$slug = array(
				"slug" => $aC->getSlug($data["title"], $post)
			);

			//merging both arrays finally to seed data
			Post::create(array_merge($data, $slug));
		}
	}
}

